// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK8155BNenze-CB6iR2J1DG8SIA-GD76k',
    appId: '1:341893581995:web:0a2704f4f3c2b57e623bee',
    messagingSenderId: '341893581995',
    projectId: 'beautyblend-7c65b',
    authDomain: 'beautyblend-7c65b.firebaseapp.com',
    databaseURL: 'https://beautyblend-7c65b-default-rtdb.firebaseio.com',
    storageBucket: 'beautyblend-7c65b.appspot.com',
    measurementId: 'G-26E3T1Y84B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8uAEuvHfRrmnYV2sBxg8iiBjdXYlTAsg',
    appId: '1:341893581995:android:99de69459aae117c623bee',
    messagingSenderId: '341893581995',
    projectId: 'beautyblend-7c65b',
    databaseURL: 'https://beautyblend-7c65b-default-rtdb.firebaseio.com',
    storageBucket: 'beautyblend-7c65b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLCLCv1LVAni1IdCOqRh0DL_WWg9HOp0',
    appId: '1:341893581995:ios:fcf4808bbaf59972623bee',
    messagingSenderId: '341893581995',
    projectId: 'beautyblend-7c65b',
    databaseURL: 'https://beautyblend-7c65b-default-rtdb.firebaseio.com',
    storageBucket: 'beautyblend-7c65b.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcLCLCv1LVAni1IdCOqRh0DL_WWg9HOp0',
    appId: '1:341893581995:ios:c2d83eb010fcc027623bee',
    messagingSenderId: '341893581995',
    projectId: 'beautyblend-7c65b',
    databaseURL: 'https://beautyblend-7c65b-default-rtdb.firebaseio.com',
    storageBucket: 'beautyblend-7c65b.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo.RunnerTests',
  );
}
